#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node.exe"  $(wslpath -w "$basedir/node_modules/grunt-cli/bin/grunt") "$@"
  ret=$?
else 
  node.exe $(wslpath -w "$basedir/node_modules/grunt-cli/bin/grunt") "$@"
  ret=$?
fi
exit $ret
