
---
root    : true

# override eslint-config-standard
parserOptions:
    ecmaVersion : 5
    ecmaFeatures:
        experimentalObjectRestSpread: false
        jsx: false
    #sourceType: "script"

env:
    amd                             : true
    browser                         : true
    jasmine                         : true

globals:
    $                               : true

rules:
    eqeqeq                          : warn
    keyword-spacing                 : warn
    space-before-blocks             : warn
    padded-blocks                   : off
